### PR TITLE
Add Tom

### PR DESCRIPTION
**Pull request by tomayac**
Add my blog URL, Twitter, and GitHub.

### CODE REVIEW

**Comment by ebidel** [comment]
@tomayac want to rebase?

**Comment by PaulKinlan** [comment]
I've got another PR - I'll add in there.

**Comment by PaulKinlan** [comment]
https://github.com/ebidel/devwebfeed/pull/17

**Comment by tomayac** [comment]
Closing my https://github.com/ebidel/devwebfeed/pull/16 then in favor of @PaulKinlan's joint https://github.com/ebidel/devwebfeed/pull/17.

**Pull request closed without merging**
